### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by mintdart**

### CODE REVIEW

**Comment by 0xngmi** [comment]
does updating deps fix anything?

**Comment by mintdart** [comment]
> does updating deps fix anything?

no figured out a way to update balance in my last commit

**Comment by mintdart** [comment]
I was checking if updating dependencies would fix stale balance in rainbowkit's wallet button, but it didn't work. Should I fix the balance update thing in a different PR and close this one?

**Comment by 0xngmi** [comment]
id avoid dep upgrades if not needed at all since yarn.lock is hard to audit

**Comment by mintdart** [comment]
okay, closing this PR

**Pull request closed without merging**
