### PR TITLE
UI fixes

### PR DESCRIPTION
**Pull request by ai-slave**
- [x] Popup for token search modal
- [x] Underlined whitespace fix on a main screen
- [x] Token is now being showed in "Amount in XXX"
- [x] Modal positioning is switched from absolute to flexbox meaning better usability
- [x] Route preview block is better spread across parent
- [x] Route preview animation isn't cut off on the sides anymore
- [x] Button to connect a wallet was missing in the swap interface
- [x] On Mobile version Routes overflowed the FAQ section
- [x] Swap and Routes box were of different height 
- [x] "Select Aggregator" scrolls to Routes tab on mobile
- [x] Swap button injected into selected route on mobile
- [x] "No routes found message"
- [x] Select aggregator is disabled before all inputs are provided

### CODE REVIEW

**Comment by ai-slave** [comment]
before
image

after
image

**Comment by ai-slave** [comment]
before
image
after 

image

**Comment by ai-slave** [comment]
Before 
image

After 
image

**Comment by ai-slave** [comment]
Before
image

After
image

**Comment by akshaynexus** [comment]
image
There seems to be a ui issue on Mobile,previously the routes would not be visible bit now it is but it overlays on top of the faq component

**Comment by ai-slave** [comment]
> image There seems to be a ui issue on Mobile,previously the routes would not be visible bit now it is but it overlays on top of the faq component

Yikes, will fix, thank you! 

Also I'd ask team to come up with a description for a swap so I can impove user expectations a little bit 
image

**Comment by ai-slave** [comment]
Before 
image

After 
image

**Comment by ai-slave** [comment]
Added connect wallet button 

Before
image

After 
image

**Comment by ai-slave** [comment]
image

**Comment by mintdart** [comment]
Screenshot
wen tokens aren't selected, can you disable select aggregator button, and hide that no routes found text?

**Comment by ai-slave** [comment]
@mintdart done, there's a little weird ```isLoading``` behaviour though, it changes true/false a few times on slow network before the request is completed.

**Comment by mintdart** [comment]
from 510px to 1020px screen width, alignment is off , for ex: 
Screenshot

**Review by mintdart — APPROVED** [review]

**Pull request merged**
